# Generated by Django 5.0.14 on 2026-03-26 04:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('followup_date', models.DateField(verbose_name='Follow-up Date')),
                ('next_followup_date', models.DateField(blank=True, null=True, verbose_name='Next Follow-up Date')),
                ('patient_status', models.CharField(choices=[('alive_no_evidence', 'Alive — No Evidence of Disease'), ('alive_with_disease', 'Alive — With Disease'), ('alive_unknown', 'Alive — Unknown Status'), ('deceased_disease', 'Deceased — Due to Disease'), ('deceased_other', 'Deceased — Other Causes'), ('lost_to_followup', 'Lost to Follow-up')], max_length=30)),
                ('contact_method', models.CharField(choices=[('clinic_visit', 'Clinic Visit'), ('phone_call', 'Phone Call'), ('letter', 'Letter'), ('home_visit', 'Home Visit'), ('other', 'Other')], default='clinic_visit', max_length=20)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight (kg)')),
                ('performance_status', models.CharField(blank=True, max_length=10, verbose_name='ECOG Performance Status')),
                ('disease_status', models.CharField(blank=True, max_length=200, verbose_name='Disease Status Notes')),
                ('complications', models.TextField(blank=True, verbose_name='Complications / Side Effects')),
                ('remarks', models.TextField(blank=True)),
                ('attending_physician', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='followups', to='cases.cancercase')),
            ],
            options={
                'verbose_name': 'Follow-up',
                'verbose_name_plural': 'Follow-ups',
                'ordering': ['-followup_date'],
            },
        ),
    ]
