# Generated by Django 5.0.14 on 2026-03-24 03:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancerCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_site', models.CharField(max_length=200, verbose_name='Primary Site')),
                ('primary_site_code', models.CharField(blank=True, max_length=10, verbose_name='ICD-O Site Code')),
                ('histology', models.CharField(max_length=200, verbose_name='Histology')),
                ('histology_code', models.CharField(blank=True, max_length=10, verbose_name='ICD-O Histology Code')),
                ('behavior', models.CharField(choices=[('0', 'Benign'), ('1', 'Uncertain'), ('2', 'In situ'), ('3', 'Malignant')], default='3', max_length=1)),
                ('laterality', models.CharField(choices=[('0', 'Not applicable'), ('1', 'Right'), ('2', 'Left'), ('3', 'Bilateral'), ('9', 'Unknown')], default='0', max_length=1)),
                ('stage', models.CharField(blank=True, max_length=20, verbose_name='Overall Stage')),
                ('tnm_t', models.CharField(blank=True, max_length=10, verbose_name='TNM - T')),
                ('tnm_n', models.CharField(blank=True, max_length=10, verbose_name='TNM - N')),
                ('tnm_m', models.CharField(blank=True, max_length=10, verbose_name='TNM - M')),
                ('diagnosis_date', models.DateField(verbose_name='Date of Diagnosis')),
                ('status', models.CharField(choices=[('active', 'Active'), ('remission', 'Remission'), ('deceased', 'Deceased'), ('lost_to_followup', 'Lost to Follow-up')], default='active', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Cancer Case',
                'verbose_name_plural': 'Cancer Cases',
                'ordering': ['-diagnosis_date'],
            },
        ),
    ]
