# Generated by Django 5.0.14 on 2026-03-25 01:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('treatment_type', models.CharField(choices=[('surgery', 'Surgery'), ('chemotherapy', 'Chemotherapy'), ('radiation', 'Radiation Therapy'), ('immunotherapy', 'Immunotherapy'), ('hormone', 'Hormone Therapy'), ('targeted', 'Targeted Therapy'), ('palliative', 'Palliative Care'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=200, verbose_name='Treatment Name / Protocol')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='Institution')),
                ('physician', models.CharField(blank=True, max_length=200, verbose_name='Attending Physician')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('discontinued', 'Discontinued')], default='planned', max_length=20)),
                ('dose', models.CharField(blank=True, max_length=100, verbose_name='Dose / Cycles')),
                ('response', models.CharField(blank=True, max_length=200, verbose_name='Treatment Response')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='cases.cancercase')),
            ],
            options={
                'verbose_name': 'Treatment',
                'verbose_name_plural': 'Treatments',
                'ordering': ['-start_date'],
            },
        ),
    ]
